### ISSUE TITLE
输入法无法使用 (版本: 2024.7.22.217)

### ISSUE THREAD

**Issue by supermecc** [stategen/helpinput#3]
刚装好这个版本的输入法, 但是在任何软件/窗口使用输入法都会导致软件/窗口崩溃, 偶尔会弹出错误窗口
![Uploading post.png…]()

**Comment by supermecc** [comment]
<img width="315" alt="post" src="https://github.com/user-attachments/assets/cf756d9a-1f7d-4462-af72-f89cd5377c04">

**Comment by stategen** [comment]
感谢反馈，这可能旧版在使用中，而新版安装后没有按提示重启造成的，后续版本已经做了版本间隔离，不会再有这种情况
